name: Auto Deploy to EC2 (Master)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Restart PM2
        env:
          NODE_ENV: "production"
          PG_SSL: "true"
          PGSSLMODE: "require"
          CORS_ORIGINS: "https://batchcode.sagartmt.com,http://localhost:5174,http://localhost:5173"
        run: |
          pm2 restart batchcode-backend --update-env || \
          pm2 start server.js --name batchcode-backend
          pm2 save
